version: "3"

services:
  db:
    container_name: back_db
    image: mysql:5.7
    restart: always
    tty: true
    environment:
      MYSQL_DATABASE: kalendar
      MYSQL_USER: user
      MYSQL_PASSWORD: password
      MYSQL_ROOT_PASSWORD: password
    ports:
      - 3306:3306
    command: --port 3306 --secure-file-priv=/data
    volumes:
      - ./mysql/initdb.d:/docker-entrypoint-initdb.d
      - ./mysql/conf.d:/etc/myaql/conf.d
        # - ./mysql/log/mysql:/var/log/mysql
      - ./mysql/data:/data

  server:
    links:
      - db
    build: ./server/
    # image: kfljoiweng/kalendar-fastapi:1.1
    tty: true
    container_name: back_fastapi
    working_dir: /usr/src/server
    ports:
      - 8080:8080
    volumes:
      - ./server/code/:/usr/src/server
     
  client:
    build: ./RNapp/
    #image: front:0.1
    container_name: front_react
    ports:
      - 19000:19000
    volumes:
      - ./server/:/var/www/server/
      - ./RNapp/:/var/www/client/
    environment:
      - EXPO_DEVTOOLS_LISTEN_ADDRESS=0.0.0.0
    tty: true
    stdin_open: true
    command: sh -c "cd test_app && npm install --save && npm i react-native-paper && npm i -g @expo/ngrok@^4.1.0 && npx expo start --tunnel"
